### ISSUE TITLE
Resolver.resolveSLD() throws TypeError: Cannot read properties of undefined (reading 'isBuffer')

### ISSUE THREAD

**Issue by ericleponner** [hedera-name-service/hns-resolution-sdk#4]
This is a follow-up of this #3.

With `hns-resolution-sdk` release 2.0.2, browser now loads HashScan correctly.

However, when passed "example.hbar", ` Resolver.resolveSLD()` throws the following exception:

    `TypeError: Cannot read properties of undefined (reading 'isBuffer')`

Browser reports 503 http status for the following URL:

    `https://mainnet.resolver.hashgraph.name/slds/domains?domain=example.hbar`

To reproduce the pb, use instructions from #3 and type "example.hbar" in search bar.

**Comment by aBFT4LIFE** [comment]
Hey @ericleponner there is a newer version of the SDK 2.0.5 https://www.npmjs.com/package/@hedera-name-service/hns-resolution-sdk/v/2.0.5#resolvergetblacklist

**Comment by ericleponner** [comment]
I confirm that HashScan now works with release 2.0.5 :-)
We pushed HNS integration in production.
You can go to [hashscan.io](https://hashscan.io) and type HNS domain names in `Search Bar`.
Don't forget to select the right network (`mainnet` or `testnet`) … ;-)
Thanks guys.

**Comment by aBFT4LIFE** [comment]
This is awesome, thanks so much @ericleponner! One thing I am noticing is the search functionality is currently limited to strictly lowercase letters when searching via HNS name. Would it be possible to remove the case sensitivity so long as the name XyZ.hbar is spelt correctly?

**Comment by aBFT4LIFE** [comment]
In addition, could we also have the name that is being searched for displayed next to, above, or below the account ID when a result is returned? 
![name result example](https://github.com/hedera-name-service/hns-resolution-sdk/assets/104216324/47d6b22c-0a4a-455a-85e5-774ba566b1f7)

**Comment by aBFT4LIFE** [comment]
@ericleponner also noticing that .boo and .cream TLD's are not presently resolving from HNS to account ID's on Hashscan as of yet. Is this something you can take a look at?

**Comment by ericleponner** [comment]
@aBFT4LIFE  is it possible to make a reverse resolution with HNS : account id => name ?

**Comment by aBFT4LIFE** [comment]
> @aBFT4LIFE
> 
> > also noticing that .boo and .cream TLD's are not presently resolving from HNS to account ID's on Hashscan as of yet. Is this something you can take a look at?
> 
> When I type `example.boo` and `example.cream` in search bar, HashScan gets 404 for both and thus report them as not found.
> 
> ```
> curl https://mainnet.resolver.hashgraph.name/slds/domains?domain=example.cream
> {"message":"Not Found"}
> curl https://mainnet.resolver.hashgraph.name/slds/domains?domain=example.boo
> {"message":"Not Found"}
> ```
> 
> Do you have valid *.boo or *.cream domain names to check ?

apologies @ericleponner appears .boo and .cream are working, the names tested initially were not in an active state.

**Comment by aBFT4LIFE** [comment]
> @aBFT4LIFE is it possible to make a reverse resolution with HNS : account id => name ?

Checking on this, will report back

**Comment by aBFT4LIFE** [comment]
> @aBFT4LIFE is it possible to make a reverse resolution with HNS : account id => name ?

Confirmed reverse lookup functionality is part of the resolver. Documentation can be found here: https://www.npmjs.com/package/@hedera-name-service/hns-resolution-sdk#resolvergetalldomainsforaccount

**Comment by aBFT4LIFE** [comment]
@ericleponner has the integration of the HNS resolver onto Hashscan been open sourced on the Hashscan repo? If so could you reply with the link to where the applicable code can be found?

**Comment by ericleponner** [comment]
@aBFT4LIFE 
HNS specific code is here:
https://github.com/hashgraph/hedera-mirror-node-explorer/blob/main/src/utils/name_service/HNS.ts
